spring.application.name=huerto-planner
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/huerto_planner
spring.datasource.username=huerto_user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
