spring.application.name=plantplan
spring.profiles.active=local

spring.datasource.url=jdbc:mysql://localhost:3306/plantplan
spring.datasource.username=huerto_user
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

plantplan.weather.base-url=https://api.open-meteo.com
plantplan.weather.forecast-days=7

plantplan.cors.allowed-origins=http://localhost:5173

plantplan.jwt.secret=i0yIHlF3skUmhFF2N2CbALqJrK62AdMtb1D9RAuzZkyMrsf4/1VTmTiT7/cSLP6B
plantplan.jwt.expiration=3600
